### ISSUE TITLE
The default value of `--logdir` is not really the current directory

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.core#16]
This is a minor issue. The help message of `legate` says the default value of `--logdir` is the current directory.  However, the actual default value of `--logdir` is where the script `legate` is installed. See https://github.com/nv-legate/legate.core/blob/9e327b771fc67401497d69aca93d24438e7b78ea/legate.py#L661

This is a bit confusing. At least for me, I thought the *current directory* means the directory where I launch the `legate`, rather than where it is installed.

If the intention is indeed to use the current directory, I believe `os.getcwd()` should work fine.

**Comment by manopapad** [comment]
Fixed, thanks for pointing this out!
