### ISSUE TITLE
Bump numpy version

### ISSUE THREAD

**Issue by bryevdv** [nv-legate/legate.core#191]
ref: https://github.com/nv-legate/legate.core/pull/189#discussion_r846573094

Suggested above to bump numpy version to a later version that supports better type annotations. 

This issue is to coordinate the version bump, any mypy-related updates that can also occur as a result, and any documentation updates.

**Comment by manopapad** [comment]
I agree, this would also allow us to remove some half-baked fallback code in cunumeric:
https://github.com/nv-legate/cunumeric/blob/branch-22.05/cunumeric/eager.py#L665-L676

From previous discussions we had concluded that numpy 1.20.0 is a reasonable version to require. Would that give us the required type annotations?

**Comment by bryevdv** [comment]
I think @magnatelee and I discovered over a slack discussion that it is 1.22 So we could certainly bump to 1.20 now and then have another issue for type cleanup when 1.22 is reasonable (or if 1.22 is reasonable right away we can update the types now too).

**Comment by magnatelee** [comment]
#206 addresses this issue.
