### ISSUE TITLE
Undefined symbol in liblgcore.so

### ISSUE THREAD

**Issue by frmrz** [nv-legate/legate.core#219]
Hi, everyone!
I'm trying to use cunumeric through legate core but I'm running into an "undefined symbol" error. I leave the trace below.

OSError: cannot load library '/home/francesco/anaconda3/envs/legate-v1/lib/libcunumeric.so': /home/francesco/anaconda3/envs/legate-v1/lib/./liblgcore.so: undefined symbol: _ZN6Legion7Runtime29perform_registration_callbackEPFvN5Realm7MachineEPS0_RKSt3setINS1_9ProcessorESt4lessIS5_ESaIS5_EEEb

I installed legate in anaconda with Python 3.8 and Cuda support. My system runs on Ubuntu 20.04.
Did anyone have the same error? Or can you point me in the direction where to solve my problem? 

Many thanks,
Francesco

**Comment by manopapad** [comment]
What command are you running, that is producing this error? Can you paste the whole output?

**Comment by manopapad** [comment]
Hi @frmrz, were you able to solve your issue?

**Comment by frmrz** [comment]
Hi @manopapad, sorry I did not reply to your first message. For this particular error, I was able to solve it by updating drivers and CUDA version on my machine. Now I'm running 515.43 and CUDA 11.7.
Anyway, I got stuck again on another error and decided to take another route for this project writing directly the cuda capable code I needed.

**Comment by manopapad** [comment]
Thanks for the update. I'm sorry legate was not helpful to you. If you have the time and inclination to open another issue describing your new problem, we would appreciate that. In any case, good luck with your project.
