### ISSUE TITLE
Conda build fails with c++17 related fix

### ISSUE THREAD

**Issue by marcinz** [nv-legate/legate.core#228]
When using conda-build:

```
/opt/conda/conda-bld/legate-core_1651611301955/_build_env/x86_64-conda-linux-gnu/include/c++/11.2.0/type_traits:71:52: error: redefinition of 'constexpr const _Tp std::integral_constant<_Tp, __v>::value'
   71 |   template<typename _Tp, _Tp __v>
      |                                                    ^                           
/opt/conda/conda-bld/legate-core_1651611301955/_build_env/x86_64-conda-linux-gnu/include/c++/11.2.0/type_traits:59:29: note: 'constexpr const _Tp value' previously declared here
   59 |       static constexpr _Tp                  value = __v;
      |     
```

This is fixed with [forcing c++17](https://github.com/nv-legate/legate.core/commit/73c76c6c7ec7e6afca6dac09ed4005f3120b5080#diff-ab8cbbde99feb80edf23d10de94559f553a11ab10e8a37a6b06909aa1238d9f3R2).

According to [this thread](https://bytemeta.vip/repo/colmap/colmap/issues/1418) this is probably related to the combination of CUDA and GCC. It's not clear whether this is a valid error or a bug. It seems that there should not be a problem since this is a standard header.

**Comment by magnatelee** [comment]
@marcinz I'm confused by this issue. isn't the issue fixed by forcing c++17, which btw is a valid thing to do since our recent decision to start requiring C++17? Is this to simply keep a note for ourselves about the existence of this issue or are we actually trying to fix it without forcing c++17?

**Comment by marcinz** [comment]
@magnatelee You are correct. I think that there was some delay in the process where the c++17 change did not make it into conda build testing. @m3vaz as well. This seems to be a non-issue anymore for me. Could you confirm? I will propose removing the workaround in a PR.

**Comment by manopapad** [comment]
With https://github.com/nv-legate/legate.core/pull/227 we are now always using C++17 (even when building Legion). The workaround on the conda recipe will be removed by https://github.com/nv-legate/legate.core/pull/229.

**Comment by magnatelee** [comment]
Would have been easier for me or anyone with no context to understand if #229 stated what the intention was.

**Comment by manopapad** [comment]
This is fixed
