### ISSUE TITLE
Update the build to request MPI_HOME explicitly

### ISSUE THREAD

**Issue by magnatelee** [nv-legate/legate.core#272]
#140 introduced a new compile dependency to MPI, but we haven't updated the install script and makefile accordingly to explicitly ask for `MPI_HOME`. It's not safe to assume that we see `mpicc` in `PATH` and use its path to locate MPI. Even if that does find `mpicc`, that might be the right one to use. I think we should always explicitly ask any dependency we use in the build. I hope the new cmake build will guarantee that the dependencies will be always resolved correctly, but until that lands, we shouldn't rely on any guessing.

**Comment by eddy16112** [comment]
When enabling the GASNet, Legion also uses `which mpicc` to detect the MPI, which is also a potential issue. However, I do not think we need to make MPI as another dependency and install it explicitly, because it really takes a lot of time to compile the MPI. So any suggestions how to fix it?

**Comment by manopapad** [comment]
The standard practice when compiling MPI programs is to use the MPI wrapper compiler (`mpicc`), which takes care of setting the appropriate flags, instead of adding `-I` and `-L` flags manually. We should follow what Legion does here https://github.com/StanfordLegion/legion/blob/master/runtime/runtime.mk#L728-L765.

**Comment by eddy16112** [comment]
Thanks, let me give a try on it.

**Comment by magnatelee** [comment]
@manopapad thanks for the suggestion. I agree that that's a better way to handle it. (I'm surprised that we weren't using mpicc for building those files that are including MPI, which is another thing that should have caught by my review...) @eddy16112 I think we should update `legate.mk` to compile the communicator files using mpicc. feel free to add a new make variable for which the makefile uses mpicc.

**Comment by eddy16112** [comment]
I created a fix https://github.com/nv-legate/legate.core/pull/274
Currently, I use mpicxx to compile all the .cc files. Do we need to use mpicxx only for communicator files?

**Comment by magnatelee** [comment]
@eddy16112 I think that's fine for now.
