### ISSUE TITLE
installation confusion with `setup.py` script

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#286]
The readme says to invoke `setup.py` with `--install-dir`. However, passing `--help` to `setup.py` only shows the argument `--prefix`. While trying to install cunumeric, I assumed that the readme had just bitrotted. However, this is incorrect, and installation with `--prefix` does something different.

**Comment by manopapad** [comment]
The plan outlined on #255 involves moving away from `setup.py` altogether (instead only using `install.py`), which will take care of this issue.

**Comment by manopapad** [comment]
We no longer suggest that users invoke `setup.py` directly.
