### ISSUE TITLE
Flag --summarize causing error: "unrecognized arguments: -lg:summarize"

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.core#3]
## Version info

legate.core: commit 18cb8fd34196f7aa8721608226a7b1b9fadfb17c
legate.numpy: 026061b

## Steps to reproduce

1. Go to legate.numpy/example
2. Execute `legate --cpus 1 --summarize ./jacobi.py`

## Expected and actual output

The expected result is the normal outputs from `jacobi.py` plus whatever the `summarize` should output.

The actual output is an error message: `jacobi.py: error: unrecognized arguments: -lg:summarize`

**Comment by manopapad** [comment]
Thank you for this report. It looks like this argument has been renamed to `-lg:numpy:summarize`, and is now handled by legate.numpy, but the old version had not been removed from the main legate launcher (I removed it just now). `-lg:numpy:summarize` should work, if you'd like to try it. Unfortunately it looks like we are not properly documenting this argument in legate.numpy, so I opened a separate issue for that: https://github.com/nv-legate/legate.numpy/issues/6.
