### ISSUE TITLE
Rebuild not triggered when debug/release option changes

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#372]
It doesn’t look a rebuild is triggered when I change from debug to release build:

```
> install.py --debug
(fresh build)
> install.py --debug
(incremental rebuild, nothing gets rebuilt)
> touch src/core/cuda/stream_pool.cu
> install.py --debug
(incremental rebuild, only stream_pull.cu gets rebuilt)
> touch src/core/cuda/stream_pool.h
> install.py --debug
(incremental rebuild, only files recursively including stream_pool.h are rebuilt)
> install.py
(nothing gets rebuilt, but I would expect a rebuild to be triggered, since we switched to release mode)
```

It looks like the new build configuration setting is not making it to cmake:

```
-- Install configuration: "Debug"
```

I tried removing the `add_touch_legate_core_ninja_build_target` optimization from `CMakeLists.txt`, but that didn't help.

I tried adding `--force-reinstall` and that didn't change the behavior.

**Comment by trxcllnt** [comment]
@manopapad are you still seeing this? I'm seeing it rebuild (and reinstall over previous build) just fine:

* [build.debug.log](https://gist.github.com/trxcllnt/5411c00765569a0cbe21841caa2610c3)
* [build.release.log](https://gist.github.com/trxcllnt/d22bd89a17a6f89702d992e12f1339c3)

**Comment by manopapad** [comment]
I still get this behavior under branch-22.12, but #455 fixes it.
