### ISSUE TITLE
`install.py` does not install files into `install_dir`

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#386]
After making the install directory to work around #385, `install.py --editable --verbose --install-dir <dir>` does not put many files into <dir>:
```
➜  legate.core git:(legate-sparse) ✗ tree ../install/                                                                                                                       (legate) 16:08:52
../install/
├── bin
│   ├── bind.sh
│   ├── legate
│   └── lgpatch
└── lib
    └── python3.9
        └── site-packages
            └── legate.core.egg-link
```
Instead, it seems to be always putting files into `./_skbuild`.

**Comment by rohany** [comment]
It seems like `--editable` is the problem. It appears to work without `--editable`.

**Comment by jjwilke** [comment]
This is working as expected with `--editable`. Instead of installing the files, it leaves an "egg-link" in the install folder that points back to the build folder. Any edits you make in the source/build folder will be automatically reflected in the installation.

**Comment by rohany** [comment]
Hold on a second -- the problem here is that if I use editable, I cannot then use `./install.py --with-core <install-dir>` with cuNumeric as there's nothing in the installation directory for cunumeric to read! That's the reason why I opened this issue in the first place.

**Comment by manopapad** [comment]
Is this still an issue, now that `--install-dir` option has been removed?

**Comment by rohany** [comment]
sounds like it's not.
