### ISSUE TITLE
base mapper does not smartly inline map regions

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#398]
The base mapper https://github.com/nv-legate/legate.core/blob/branch-22.10/src/core/mapping/base_mapper.cc#L1268 always inline maps regions in system memory, even if the system memory is very small compared to NUMA memories on the node. I'm working around this right now by changing this logic to inline map into socket memories if they exist.

**Comment by rohany** [comment]
The same problem arises with the `map_copy` overload.

**Comment by rohany** [comment]
Same with `map_partition`.

**Comment by manopapad** [comment]
@rohany this should be fixed with #452, can you confirm?

**Comment by rohany** [comment]
That particular code is not running right now, but from looking at the PR it should be fixed. Will close this and open later if it's a problem.
