### ISSUE TITLE
How to correctly use OpenMP backend?

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.core#4]
My test machine has only one CPU socket. This CPU has 6 physical cores and a total of 12 logical cores. Using the script `legate` (i.e., `legate.py`), how to correctly specify flags for OpenMP, especially the flags `--cpus`, `--omps`, and `--ompthreads` (and probability also `--utility`)? Or is there documentation about how to use these flags? I read Legion's [documentation](https://legion.stanford.edu/profiling/#machine-configuration) but still unclear how to use OpenMP.

No matter how I change the flags, the example code always runs (and I assume the results are correct). However, sometimes I get warnings like `... {4}{threads}: reservation (blahblahblah) cannot be satisfied ...` and have no clue how to fix it. For example, when I ran the `jacobi.py` example with
```
$ legate --cpus 1 --omps 1 --ompthreads 4 --utility 0 jacobi.py  
```
I got `[0 - 7fb341387f00]    0.000120 {4}{threads}: reservation ('dedicated worker (generic) #2') cannot be satisfied`. This is confusing, as the system should not be oversubscribed by just 4 OMP threads. I checked the resource reservation by running the application directly with `legion_python jacobi.py -ll:py 1 -ll:cpu 1 -ll:ocpu 1 -ll:othr 4 -ll:util 0 -ll:show_rsvr` and got

```
core map {
  domain 0 {
    core 0 { ids=<0> alu=<6> fpu=<6> ldst=<6> }
    core 1 { ids=<1> alu=<7> fpu=<7> ldst=<7> }
    core 2 { ids=<2> alu=<8> fpu=<8> ldst=<8> }
    core 3 { ids=<3> alu=<9> fpu=<9> ldst=<9> }
    core 4 { ids=<4> alu=<10> fpu=<10> ldst=<10> }
    core 5 { ids=<5> alu=<11> fpu=<11> ldst=<11> }
    core 6 { ids=<6> alu=<0> fpu=<0> ldst=<0> }
    core 7 { ids=<7> alu=<1> fpu=<1> ldst=<1> }
    core 8 { ids=<8> alu=<2> fpu=<2> ldst=<2> }
    core 9 { ids=<9> alu=<3> fpu=<3> ldst=<3> }
    core 10 { ids=<10> alu=<4> fpu=<4> ldst=<4> }
    core 11 { ids=<11> alu=<5> fpu=<5> ldst=<5> }
  }
}
OMP0 proc 1d00000000000001 (master): allocated <>
OMP0 proc 1d00000000000001 (worker 1): allocated <>
CPU proc 1d00000000000000: allocated <>
dedicated worker (generic) #1: allocated <>
dedicated worker (generic) #2: allocated <>
OMP0 proc 1d00000000000001 (worker 3): allocated <>
Python-1 proc 1d00000000000002: allocated <>
OMP0 proc 1d00000000000001 (worker 2): allocated <>
```

And when I did `legion_python jacobi.py -ll:py 1 -ll:cpu 1 -ll:ocpu 1 -ll:othr 3 -ll:util 0 -ll:show_rsrv`, I got no warning and this
```
blah blah blah

OMP0 proc 1d00000000000001 (master): allocated <0>
OMP0 proc 1d00000000000001 (worker 1): allocated <1>
CPU proc 1d00000000000000: allocated <3>
dedicated worker (generic) #1: allocated <5,11>
dedicated worker (generic) #2: allocated <5,11>
Python-1 proc 1d00000000000002: allocated <4>
OMP0 proc 1d00000000000001 (worker 2): allocated <2>
```

It seems except for the 3 or 4 threads requested by OMP, there are also many other processes using resources (CPU proc, dedicated worker 1 & 2, Python-1, and utility proc if enabled). And each process has to be bound to a physical core? Is this the reason why 4 OMP threads cause the resources oversubscribed? If so, how to maximize the performance and resource usage when using OMP? (e.g., dedicating all physical cores to OMP?)

Thanks in advance, and I apologize for so many question :P

**Comment by manopapad** [comment]
Thank you for your continued interest in Legate, and your patience as we iron things out post-release.

Core allocation is unfortunately not straightforward, and is not actually managed by us but by the Realm level below us.

Legate asks Realm to allocate `--cpus` cores to be CPU processors (these run non-OpenMP CPU code), 1 core to be the Python processor (this runs the Python interpreter) and `--ompthreads` cores to the OpenMP runtime. These are pinned processors, i.e. the cores they get assigned to cannot be used for anything else. The remaining cores are used to perform Legion runtime analysis (utility processors), launch GPU kernels (GPU processor) and for Realm workers. These allocations are flexible, i.e. the same core may context-switch between any of these workloads.

The problem you're seeing is that Realm by default doesn't consider SMT when assigning cores to pinned processors (CPU, Python and OpenMP). This is likely done to avoid having two "workhorse" threads share an arithmetic unit. Based on your `-ll:show_rsrv` output, on your machine core N and N+6 form an SMT pair, therefore you can only get up to 3 OpenMP worker threads (core 0 was assigned to an OpenMP worker, thus core 6 is unusable etc.).

Note that even if Realm cannot find enough cores to satisfy your requested allocation, execution will still proceed as normal, but without processor pinning.

Try the following options:
* Drop the CPU processor (`--cpus 0`), giving you an extra OpenMP thread. Legate.numpy should not be using the single-core code path at all if an OpenMP processor is present. If you see any mapping issues in this mode you can work around it with `-ll:okindhack`, which tells Realm to expose the OpenMP master thread also as a CPU processor (and please let us know of the mapping issue, so we can fix it properly).
* Run with `-ll:ht_sharing`, which tells Realm to use both virtual cores in an SMT pair for pinned processors. Note that performance degradation is possible (but it would be interesting to know if any degradation you see is any different from your typical experience with OpenMP codes on your machine).

On a slightly related topic, if you have time please try using the scripts at https://github.com/nv-legate/quickstart. These are supposed to detect the number of physical cores on the local machine and set the number of OpenMP threads appropriately. I would be interested to know if they work on your machine.

CC'ing @streichler for visibility

**Comment by streichler** [comment]
One tiny tweak to what @manopapad said: to tell Realm to consider hyperthreads to be separate execution resources, you need `-ll:ht_sharing 0`.  (The default is `-ll:ht_sharing 1`.)

**Comment by piyueh** [comment]
Thank you @manopapad and @streichler ! I think I understand it now.

1. Yes, using `--cpus 0` (or `-ll:cpu 0` with `legion_python`) gives me errors. I need to also use `-ll:okindhack`, and then everything works. The errors (different errors when w/ or w/o utility processes): 
  
    1. w/o utility processes (`legion_python -ll:py 1 -ll:cpu 0 -ll:ocpu 1 -ll:othr 1 -ll:util 0 ./jacobi.py`)
        ```
        [0 - 7f3fb47e8f00]    0.000350 {5}{runtime}: [error 131] LEGION ERROR: Machine model contains no
        CPU processors and no utility processors! At least one CPU or one utility processor is required
        for Legion.
        ```
    2. w/ utility processes (`legion_python -ll:py 1 -ll:cpu 0 -ll:ocpu 1 -ll:othr 1 -ll:util 2 ./jacobi.py`)
        ![20210427-020917EDT](https://user-images.githubusercontent.com/7220966/116193590-9879fc00-a6fd-11eb-8b39-23a1e7c230fe.png)
       
2. `-ll:ht_sharing 0` is working as you described. I'm still playing around with it and example codes. Will update you if I find anything interesting.

Thanks again!
