### ISSUE TITLE
install.py --editable doesn't install legion_python under $CONDA_PREFIX

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#410]
I do see it under these locations:

```
legate.core/_skbuild/linux-x86_64-3.8/cmake-install/bin/legion_python
legate.core/_skbuild/linux-x86_64-3.8/cmake-build/_deps/legion-build/bin/legion_python
legate.core/_skbuild/linux-x86_64-3.8/cmake-build/_deps/legion-build/bindings/python/CMakeFiles/legion_python.dir
```

but not anywhere under `$CONDA_PREFIX`

**Comment by jjwilke** [comment]
Is `legate` not working for you? This should still successfully find `legion_python` in the build folder and run.

**Comment by manopapad** [comment]
`legate` is working. This just came up as we were debugging another person's build issues, and it sounded possibly like a bug that `legion_python` was not getting installed, so I opened this issue. I've confirmed that indeed this is expected behavior for editable installs.
