### ISSUE TITLE
`mypy` error on Mac

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#435]
I see this error running `mypy` on my mac:
```
legate/util/system.py: note: In member "cpus" of class "System":
legate/util/system.py:94:9: error: Statement is unreachable  [unreachable]
```

I think that `mypy` can tell that the platform is `darwin` so it thinks that the branch is always true.

**Comment by rohany** [comment]
yup, that works.

**Comment by bryevdv** [comment]
:tada: in the PR, please leave a short comment above the else noting that it is required for `mypy`
