### ISSUE TITLE
install.py should pick up changes to legion without forcing --clean

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#491]
Right now, making a change to legion and using `install.py` requires using `--clean` to rebuild, rather than it picking up the change. It would be great if single-file changes to legion did not require a full rebuild.

**Comment by manopapad** [comment]
I thought we were doing this correctly at this point, after https://github.com/nv-legate/legate.core/pull/455 and https://github.com/nv-legate/legate.core/pull/442 were merged. And this has been working for me AFAICT. Can you post some output where a change in legion fails to trigger recompilation?

**Comment by rohany** [comment]
What command do you do? I do `./install.py --verbose --editable --legion-src-dir legion --arch pascal --conduit ibv --network gasnet1 --debug-release` to rebuild the core.

**Comment by rohany** [comment]
actually never mind, this is working, i think my paths got messed up.
