### ISSUE TITLE
`ReturnValues` should not access GPU streams when not on TOC proc

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#501]
This code: https://github.com/nv-legate/legate.core/blob/branch-22.12/src/core/task/return.cc#L212 mistakenly tries to access CUDA streams when not tied to a GPU task.

**Comment by magnatelee** [comment]
@rohany thanks for reporting this. does this cause any crash or weird behavior?

**Comment by rohany** [comment]
It caused a crash for me when I ran with significantly more cpus or omps than gpus per node. I ran into it when preparing a reproducer that had 16 ranks per node.
