### ISSUE TITLE
-rpath-link flag added by RAPIDS is not valid for Mac linker

### ISSUE THREAD

**Issue by jjwilke** [nv-legate/legate.core#609]
The latest RAPIDS has added some logic to `rapids_cmake_support_conda_env` that breaks Mac builds by adding `-rpath-link`, but this is not a valid flag for the Mac linker.  This should ideally be fixed in RAPIDS, but may require us to revert the RAPIDS version number we use.

**Comment by trxcllnt** [comment]
@robertmaynard

**Comment by trxcllnt** [comment]
And if we need to have green macOS builds, we should be compiling on macOS in CI :sweat_smile:

**Comment by jjwilke** [comment]
yeah, agreed. We don't want to waste too much effort on something that isn't officially supported or tested. Generally, most Mac issues can be fixed by setting CMake options and customizing the logic to fix, e.g. rpath issues. In this case, Mac is just broken and you would have to manually edit the Makefile/ninja file to get it to build.

**Comment by robertmaynard** [comment]
Should be fairly easy to update rapids-cmake to only inject `-rpath-link` when we think the linker supports it

**Comment by robertmaynard** [comment]
https://github.com/rapidsai/rapids-cmake/pull/384

**Comment by manopapad** [comment]
> And if we need to have green macOS builds, we should be compiling on macOS in CI 😅

We're getting there.

**Comment by manopapad** [comment]
It looks like the linked rapids-cmake PR has been merged. Are we good to close this?

**Comment by trxcllnt** [comment]
Yeah, should be.
