### ISSUE TITLE
lgpatch doesn't work

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#614]
As reported by @betatim on https://github.com/nv-legate/cunumeric/issues/829:

```
$ lgpatch -patch numpy scikit-learn/mlp.py
usage: lgpatch [-patch PATCH [PATCH ...]] PROG
lgpatch: error: the following arguments are required: PROG
```

**Comment by manopapad** [comment]
If it's easy, it would probably make more sense to accept `-patch` before the script name, so we don't mess with the script's arguments. But if it's a lot of work, then just updating the documentation to reflect the current behavior would be fine (there's `-patch:help`, but that's pretty hard to get to, so likely the place to update the docs would be the cuNumeric Sphinx docs).

**Comment by bryevdv** [comment]
The (sphinx) docs are actually correct for the current behavior, but I agree having the `-patch` first would be preferable. As long as we are changing it can we switch to `--patch` which argparse will handle better?

**Comment by manopapad** [comment]
Absolutely. And if we could make `lgpatch -h` print out the full help message, i.e. what is printed today with `-patch:help`:

```
~> lgpatch -patch:help
usage: lgpatch [-patch PATCH [PATCH ...]] PROG

Patch existing libraries with legate equivalents.

Currently the following patching can be applied:

    numpy -> cunumeric

positional arguments:
  PROG                  The legate program to run

optional arguments:
  -patch PATCH [PATCH ...]
                        Patch the specified libraries

Any additional command line arguments are passed on to PROG as-is
```

instead of just:

```
~> lgpatch -h
usage: lgpatch [-patch PATCH [PATCH ...]] PROG
lgpatch: error: the following arguments are required: PROG
```

even better.
