### ISSUE TITLE
"OpenMP_CXX not found" on aarch64 with separate legion build

### ISSUE THREAD

**Issue by 1193749292** [nv-legate/legate.core#642]

**Comment by 1193749292** [comment]
Build on aarch64: 
build legion command: cmake .. -S /xxx/legion/ -D CMAKE_INSTALL_PREFIX=../install -D REALM_USE_OPENMP=ON -D Legion_USE_OpenMP=ON -D REALM_OPENMP_SYSTEM_RUNTIME=ON -D Legion_OpenMP_SYSTEM_RUNTIME=ON -D REALM_USE_MPI=ON -DLegion_NETWORKS=mpi -D Legion_MPI_INTEROP=ON -B ../build

build legate.core command: ./install.py --openmp --network mpi --with-legion /xxx/legion/install/ -v --nocuda  --march native

Then build the legate, error not find "OpenMP_CXX"

**Comment by manopapad** [comment]
@trxcllnt any idea what might have gone wrong here?

@1193749292 can you share the full failed legate.core build output? Does it work if you just invoke install.py without --with-legion (which will let legate.core build legion internally)?

**Comment by 1193749292** [comment]
@manopapad Install on aarch64,
build legion command: cmake .. -S /home/xxx/hpc/legion/ -D CMAKE_INSTALL_PREFIX=../install -D REALM_USE_OPENMP=ON -D Legion_USE_OpenMP=ON -D REALM_OPENMP_SYSTEM_RUNTIME=ON -D Legion_OpenMP_SYSTEM_RUNTIME=ON -D REALM_USE_MPI=ON -DLegion_NETWORKS=mpi -D Legion_MPI_INTEROP=ON -B ../build

build legate.core command: ./install.py --openmp --network mpi --with-legion /home/xxx/hpc/legion/build/ -v --nocuda --march native

  --------------------------------------------------------------------------------
  -- Performing Test COMPILER_SUPPORTS_MVSX - Failed
  -- Configuring done (27.4s)
  CMake Error at /opt/home/xxx/hpc/legion/build/LegionTargets.cmake:56 (set_target_properties):
    The link interface of target "Legion::RealmRuntime" contains:

      OpenMP::OpenMP_CXX

    but the target was not found.  Possible reasons include:

      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing.

  Call Stack (most recent call first):
    /opt/home/xxx/hpc/legion/build/LegionConfigCommon.cmake:40 (include)
    /opt/home/xxx/hpc/legion/build/LegionConfig.cmake:2 (include)
    _skbuild/linux-aarch64-3.9/cmake-build/_deps/rapids-cmake-src/rapids-cmake/find/package.cmake:114 (find_package)
    cmake/thirdparty/get_legion.cmake:50 (rapids_find_package)
    cmake/thirdparty/get_legion.cmake:195 (find_or_configure_legion)
    legate_core_cpp.cmake:112 (include)
    CMakeLists.txt:97 (include)


  -- Generating done (0.0s)
  CMake Warning:
    Manually-specified variables were not used by the project:

      Legion_EMBED_GASNet_CONFIGURE_ARGS
      PYTHON_EXECUTABLE
      PYTHON_INCLUDE_DIR
      PYTHON_LIBRARY
      PYTHON_VERSION_STRING
      Python_EXECUTABLE
      Python_FIND_REGISTRY
      Python_INCLUDE_DIR
      Python_ROOT_DIR


  CMake Generate step failed.  Build files cannot be regenerated correctly.
  Traceback (most recent call last):
    File "/tmp/pip-build-env-vyrk4unl/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 634, in setup
      env = cmkr.configure(
    File "/tmp/pip-build-env-vyrk4unl/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 332, in configure
      raise SKBuildError(

  An error occurred while configuring with CMake.
    Command:
      /tmp/pip-build-env-vyrk4unl/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake /opt/home/xxx/hpc/legate.core -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/opt/home/xxx/hpc/legate.core/_skbuild/linux-aarch64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.13 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-vyrk4unl/overlay/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/xxx/anaconda3/bin/python3 -DPYTHON_INCLUDE_DIR:PATH=/home/xxx/anaconda3/include/python3.9 -DPYTHON_LIBRARY:PATH=/home/xxx/anaconda3/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/home/xxx/anaconda3/bin/python3 -DPython_ROOT_DIR:PATH=/home/xxx/anaconda3 -DPython_INCLUDE_DIR:PATH=/home/xxx/anaconda3/include/python3.9 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/xxx/anaconda3/bin/python3 -DPython3_ROOT_DIR:PATH=/home/xxx/anaconda3 -DPython3_INCLUDE_DIR:PATH=/home/xxx/anaconda3/include/python3.9 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-vyrk4unl/overlay/lib/python3.9/site-packages/ninja/data/bin/ninja --log-level=VERBOSE -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_MARCH=native -DCMAKE_CUDA_ARCHITECTURES=NATIVE -DLegion_MAX_DIM=4 -DLegion_MAX_FIELDS=256 -DLegion_SPY=OFF -DLegion_BOUNDS_CHECKS=OFF -DLegion_USE_CUDA=OFF -DLegion_USE_OpenMP=ON -DLegion_USE_LLVM=OFF -DLegion_NETWORKS=mpi -DLegion_USE_HDF5=OFF -DLegion_USE_Python=ON -DLegion_Python_Version=3.9.13 -DLegion_REDOP_COMPLEX=ON -DLegion_REDOP_HALF=ON -DLegion_BUILD_BINDINGS=ON -DLegion_BUILD_JUPYTER=ON '-DLegion_EMBED_GASNet_CONFIGURE_ARGS="--with-ibv-max-hcas=8"' -DGASNet_ROOT_DIR=/opt/home/xxx/hpc/gasnet/release_mpich -DGASNet_CONDUIT=mpi -DLegion_ROOT=/opt/home/xxx/hpc/legion/build -Dlegate_core_LEGION_REPOSITORY=https://gitlab.com/StanfordLegion/legion.git -Dlegate_core_LEGION_BRANCH=04cf06a2 -DCMAKE_BUILD_TYPE:STRING=Release --log-level=VERBOSE -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_MARCH=native -DCMAKE_CUDA_ARCHITECTURES=NATIVE -DLegion_MAX_DIM=4 -DLegion_MAX_FIELDS=256 -DLegion_SPY=OFF -DLegion_BOUNDS_CHECKS=OFF -DLegion_USE_CUDA=OFF -DLegion_USE_OpenMP=ON -DLegion_USE_LLVM=OFF -DLegion_NETWORKS=mpi -DLegion_USE_HDF5=OFF -DLegion_USE_Python=ON -DLegion_Python_Version=3.9.13 -DLegion_REDOP_COMPLEX=ON -DLegion_REDOP_HALF=ON -DLegion_BUILD_BINDINGS=ON -DLegion_BUILD_JUPYTER=ON -DLegion_EMBED_GASNet_CONFIGURE_ARGS=--with-ibv-max-hcas=8 -DGASNet_ROOT_DIR=/opt/home/xxx/hpc/gasnet/release_mpich -DGASNet_CONDUIT=mpi -DLegion_ROOT=/opt/home/xxx/hpc/legion/build -Dlegate_core_LEGION_REPOSITORY=https://gitlab.com/StanfordLegion/legion.git -Dlegate_core_LEGION_BRANCH=04cf06a2
    Source directory:
      /opt/home/xxx/hpc/legate.core
    Working directory:
      /opt/home/xxx/hpc/legate.core/_skbuild/linux-aarch64-3.9/cmake-build
  Please see CMake's output for more information.
  error: subprocess-exited-with-error
  
  × Building wheel for legate.core (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/xxx/anaconda3/bin/python3 /home/xxx/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpldq_tk45
  cwd: /opt/home/xxx/hpc/legate.core
  Building wheel for legate.core (pyproject.toml) ... error
  ERROR: Failed building wheel for legate.core
Failed to build legate.core
ERROR: Could not build wheels for legate.core, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 431, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for legate.core, which is required to install pyproject.toml-based projects
Remote version of pip: 23.0.1
Local version of pip:  22.2.2
Was pip installed by pip? False
Removed build tracker: '/tmp/pip-build-tracker-tw83ncms'
Traceback (most recent call last):
  File "/opt/home/xxx/hpc/legate.core/./install.py", line 772, in <module>
    driver()
  File "/opt/home/xxx/hpc/legate.core/./install.py", line 768, in driver
    install(unknown=unknown, **vars(args))
  File "/opt/home/xxx/hpc/legate.core/./install.py", line 484, in install
    execute_command(pip_install_cmd, verbose, cwd=legate_core_dir, env=cmd_env)
  File "/opt/home/xxx/hpc/legate.core/./install.py", line 75, in execute_command
    subprocess.check_call(args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xxx/anaconda3/bin/python3', '-m', 'pip', 'install', '--root', '/', '--prefix', '/home/xxx/anaconda3', '--upgrade', '.', '-vv']' returned non-zero exit status 1.
  --------------------------------------------------------------------------------
/opt/home/xxx/hpc/legion/build/LegionTargets.cmake
![image](https://user-images.githubusercontent.com/128877897/227822418-596c9954-6297-415b-a3b9-1c6e6f8451e5.png)

**Comment by 1193749292** [comment]
@manopapad

**Comment by manopapad** [comment]
Thanks for the output, I'll ask @trxcllnt or @jjwilke to take a look.

@1193749292 in the meantime, could you please try building legate.core with `./install.py --openmp --network mpi -v --nocuda --march native --clean`? This should skip your previously built Legion, and do a private recursive build of Legion just for Legate.core. I just want to see if the issue is with Legion itself, or if you're missing some flag when you're building Legion separately.

Although, IIRC aarch64 is not a supported Legion architecture, so even if this works you might still face issues going forward, is that correct @lightsighter ?

**Comment by trxcllnt** [comment]
This is a bug in Legion's CMake. When you build Legion with `-DLegion_OpenMP_SYSTEM_RUNTIME=ON`, Legion [searches for](https://gitlab.com/StanfordLegion/legion/-/blob/3354a70192188e5eca7d0c4f96fc3b370541c8fc/CMakeLists.txt#L249-251) and [links Realm to `OpenMP::OpenMP_CXX`](https://gitlab.com/StanfordLegion/legion/-/blob/3354a70192188e5eca7d0c4f96fc3b370541c8fc/runtime/CMakeLists.txt#L665-667). This is why `OpenMP::OpenMP_CXX` is listed in the public interface of the Realm target in @1193749292's screenshot.

But Legion's package config files (i.e. `LegionConfig.cmake`, `LegionConfigCommon.cmake`, `LegionTargets.cmake`, etc.) don't do a `find_package(OpenMP REQUIRED COMPONENTS CXX)` before referencing the `OpenMP:OpenMP_CXX` target is in Realm's public interface.

We can paper over this by searching for OpenMP in legate_core's package before finding Legion, but the fix should really go in Legion.

**Comment by 1193749292** [comment]
Thank you for your answer. I replaced "--with-legion" with "--legion-src-dir" and finally installed successfully. However, the following situation occurs during the process(Otherwise, legion-04cf06a2 will be downloaded automatically, Of course, you can specify a branch, and the same problem as "--legion-src-dir" will be encountered.):
-----------------------------------------------------
/opt/home/xxx/hpc/legate.core-branch-22.12/src/core/data/store.h:165:35: error: ‘OutputRegion’ in
namespace ‘Legion’ does not name a type
165 |  OutputRegionField(const Legion::OutputRegion& out, Legion::FieldID fid);
/opt/home/xxx/hpc/legate.core-branch-22.12/src/core/data/store.h:196:11: error: ‘OutputRegion' in
namespace ‘Legion' does not name a type
-----------------------------------------------------
This is the comparison of base_mapper.h, which I replaced with the branch on the left.
![image](https://user-images.githubusercontent.com/128877897/228107111-f78e549d-9b81-4cad-9902-0e6e4f7a6c09.png)
![image](https://user-images.githubusercontent.com/128877897/228108179-9e54df9d-1512-4d5a-8345-c2f3c506f839.png)

Legion-branch-22.09 was also used before the installation was successful.

**Comment by 1193749292** [comment]
@trxcllnt Thank you for your answer. I added "find_package(OpenMP)", which solved the error.

**Comment by manopapad** [comment]
> We can paper over this by searching for OpenMP in legate_core's package before finding Legion, but the fix should really go in Legion.

@trxcllnt Could you please take a crack at this? Or if you don't have time, maybe just open a Legion issue telling them what they need to do?

@1193749292 You might have hit some legion/legate.core incompatibility. Legate often uses cutting edge features from Legion, so you will typically need to combine a Legate version with a Legion version from about the same time. This is somewhat encoded in https://github.com/nv-legate/legate.core/blob/branch-23.05/cmake/versions.json#L8-L11, but that only controls what version of legion is pulled when you let legate.core build it recursively. It doesn't check the version of a legion installation that you pass through `--with-legion`.

**Comment by 1193749292** [comment]
@manopapad Thank you for your answer.

**Comment by 1193749292** [comment]
legion branch  control_replication
legate.core branch-22.12
Using these two branches does not have these problems.
