### ISSUE TITLE
Getting `mathtypes/half.h` error while building a downstream library with legate.core

### ISSUE THREAD

**Issue by cjnolet** [nv-legate/legate.core#704]
I'm installing legate.core using this command (I'm using an RTX A6000 w/ CUDA 11.8):
```
./install.py --cuda --with-cuda /usr/local/cuda/ --arch 86
```

And while building this library, I'm getting a couple different errors:
```
[ 95%] Built target legate_raft_generate_install_info_py
In file included from /home/cjnolet/miniconda3/envs/legate_042423/include/mathtypes/complex.h:45,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legion/legion_redop.h:25,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legion.h:59,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legate/legate.h:25,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/../legate_library.h:19,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/../legate_raft.h:4,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/kmeans_fit_task.cc:5:
/home/cjnolet/miniconda3/envs/legate_042423/include/mathtypes/half.h:558:8: error: redefinition of 'struct __half'
  558 | struct __half
      |        ^~~~~~
```

```
/usr/local/cuda/include/cuda_fp16.hpp:185:5: note:   candidate expects 0 arguments, 2 provided
/usr/local/cuda/include/cuda_fp16.hpp:179:26: note: candidate: 'constexpr __half::__half(const __half&)'
  179 | struct __CUDA_ALIGN__(2) __half {
      |                          ^~~~~~
/usr/local/cuda/include/cuda_fp16.hpp:179:26: note:   candidate expects 1 argument, 2 provided
/usr/local/cuda/include/cuda_fp16.hpp:179:26: note: candidate: 'constexpr __half::__half(__half&&)'
/usr/local/cuda/include/cuda_fp16.hpp:179:26: note:   candidate expects 1 argument, 2 provided
In file included from /home/cjnolet/miniconda3/envs/legate_042423/include/mathtypes/complex.h:45,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legion/legion_redop.h:25,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legion.h:59,
                 from /home/cjnolet/miniconda3/envs/legate_042423/include/legate/legate.h:25,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/../legate_library.h:19,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/../legate_raft.h:4,
                 from /home/cjnolet/workspace/rapids_projects/legate.raft/cpp/src/task/kmeans_fit_task.cc:5:
/home/cjnolet/miniconda3/envs/legate_042423/include/mathtypes/half.h:694:10: error: 'struct __half' has no member named 'set_raw'
  694 |   result.set_raw(temp);
      |          ^~~~~~~
```

The task in question is not including anything special. Any ideas about what could be causing this? We found [this issue](https://github.com/nv-legate/legate.core/issues/123), which is pretty old and seems to indicate the architecture could be causing the problem, but we switched from using `--arch ampere` to `--arch 86` and the problem still persists.

**Comment by cjnolet** [comment]
I figured out that this is being caused whenever there are headers that rely on CUDA (both runtime and device APIs trigger this). Compilling those bits in a separate `.cu` file fixed this

**Comment by manopapad** [comment]
I believe the assumption in Legion is that `.cc` files are compiled by the host compiler (and do not contain CUDA/HIP API calls), whereas `.cu` files are compiled by nvcc/hipcc (and may contain CUDA API calls). Thus `legion.h` will include CUDA/HIP headers (and adapt any definitions accordingly) if and only if `__CUDACC__`/`__HIPCC__` is defined.

If these macros are not defined, `legion.h` will provide its custom definition for `__half`, which will conflict with the one from `cuda_fp16.hpp`, in case the same compilation unit manually includes CUDA headers.

Ideally we should be able to give a more informative error message if `legion.h` detects that a CUDA header has been included (I assume `cuda.h` is a good one to check for, by testing whether its include guard `__cuda_cuda_h__` is defined, but @m3vaz to comment). But this presumably still won't catch cases where the compilation unit includes CUDA headers *after* `legion.h`.
