### ISSUE TITLE
conda env generation script should install skbuild

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#706]
it doesnt

**Comment by rohany** [comment]
same with cython

**Comment by manopapad** [comment]
It does tho?

https://github.com/nv-legate/legate.core/blob/branch-23.05/scripts/generate-conda-envs.py#L107

https://github.com/nv-legate/legate.core/blob/branch-23.05/scripts/generate-conda-envs.py#L112

**Comment by rohany** [comment]
hmmmmmm. You're right, but for some reason when I did the build, I had to install those packages manually -- I got errors during my build and execution that they were missing so I made the issue.

I'm not sure what went wrong, maybe my conda package installations failed and I didn't notice. I'll close this for now and re-open if I can reproduce it later.
