### ISSUE TITLE
Launcher: detect when externally launched

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#829]
Currently if Legate is launched externally, the user still has to specify the number of nodes/ranks to the launcher, otherwise the launcher will think this is an execution on 1 node and 1 rank (the defaults), and disable networking, leading to the spawned processes executing independently, instead of performing a joint execution:

```
(a) iblis:~/a/cunumeric> cat b.py
from legate.core import get_machine
print(f"there are {len(get_machine())} processors available")

# wrong: separate execution
(a) iblis:~/a/cunumeric> mpirun -n 2 legate --cpus 3 b.py
[0 - 7f2e3e23b000]    0.000141 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
[0 - 7f41dae27000]    0.000141 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
there are 3 processors available
there are 3 processors available

# correct: joint execution
(a) iblis:~/a/cunumeric> mpirun -n 2 legate --ranks-per-node 2 --cpus 3 b.py
*** WARNING (proc 0): Running with multiple processes per host without shared-memory communication support (PSHM).  This can significantly reduce performance.  Please re-configure GASNet using `--enable-pshm` to enable fast intra-host comms.
[0 - 7f1a6e7fb000]    0.000159 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
[1 - 7fdf9d24e000]    0.000159 {4}{threads}: reservation ('CPU proc 1d00010000000003') cannot be satisfied
there are 6 processors available
```

See https://github.com/nv-legate/cunumeric/issues/1039 for a motivating example.

When `--launcher` is `none`, we could check for the presence of the launcher rank envvars (`OMPI_COMM_WORLD_RANK` etc.), and if found deduce that we are in a parallel launch. I suggest also printing out on the first rank (`detected_rank_id == 0`) that we detected an external launch in this case.

We would need to change the logic for things like setting `-ll:networks none` from `ranks > 1` to `is_in_parallel_launch`, as we now have a case where `ranks` is nominally 1, but we are inside a parallel launch.

**Comment by bryevdv** [comment]
> When --launcher is none, we could check for the presence of the launcher rank envvars (OMPI_COMM_WORLD_RANK etc.), and if found deduce that we are in a parallel launch. I suggest also printing out on the first rank (detected_rank_id == 0) that we detected an external launch in this case.

I think the simplest thing might be to replace the "shared" arg spec:
```python
multi_node.add_argument(RANKS_PER_NODE.name, **RANKS_PER_NODE.kwargs)
```
with one that has something like:
```python
default=detect_ranks_per_node()
```
where `detect_ranks_per_node` looks for all the various env vars (and returns the shared default if none are found). 

Intercepting and updating `ranks_per_node` earlier that way should cause the computed value `MultiNode.ranks`, and everything else downstream based on that, to continue to function as expected without any changes.

**Comment by bryevdv** [comment]
Well, scratch that, I was mis-remembering what was in the env vars. I guess it's too much to hope that the launchers also set an env var with total ranks that we could inspect in the manner described above?

**Comment by manopapad** [comment]
> I guess it's too much to hope that the launchers also set an env var with total ranks that we could inspect in the manner described above?


Actually there are, but it's a little wonky (some define `num_ranks` & `num_nodes`, others define `num_nodes` & `ranks_per_node`, and Intel MPI only reports `num_ranks`...). Here's my best guess at what the inference logic might look like:

```
nodes = args.nodes
ranks_per_node = args.ranks_per_node

if $OMPI_COMM_WORLD_SIZE is set:
  if nodes is None:
    nodes = $OMPI_COMM_WORLD_SIZE
  if ranks_per_node is None:
    ranks_per_node = $OMPI_COMM_WORLD_LOCAL_SIZE

elif $MV2_COMM_WORLD_SIZE is set:
  if nodes is None:
    nodes = $MV2_COMM_WORLD_SIZE
  if ranks_per_node is None:
    ranks_per_node = $MV2_COMM_WORLD_LOCAL_SIZE

elif $PMI_SIZE is set:
  ranks = $PMI_SIZE
  if ranks_per_node is None:
    # TODO: this may be wrong, but IntelMPI doesn't report this
    ranks_per_node = 1
  if nodes is None:
    nodes = ranks // ranks_per_node
  assert nodes * ranks_per_node == ranks

elif $SLURM_NTASKS is set:
  ranks = $SLURM_NTASKS
  nodes = $SLURM_JOB_NUM_NODES
  assert ranks % nodes == 0
  ranks_per_node = ranks // nodes
```

> some kind of new default value

I agree, we would need to change the default values for `--nodes` & `--ranks-per-node` to mean "auto-detect", and if auto-detection fails (because we're not in an external launch) set both to 1.

**Comment by bryevdv** [comment]
@manopapad Can we punt on auto-detect for PMI if PMI doesn't provide all the necessary info to auto-detect anyway? If so, then auto-detection can happen via defaults replacement:
```python
def detect_multi_node_config():
    nodes_kw, ranks_per_node_kw = dict(NODES.kwargs), dict(RANKS_PER_NODE.kwargs)

    where = None

    if (nodes := getenv("OMPI_COMM_WORLD_SIZE")):
        if (ranks_per_node := getenv("OMPI_COMM_WORLD_LOCAL_SIZE")):
            where = "OMPI"

    elif (nodes := getenv("MV2_COMM_WORLD_SIZE")):
        if (ranks_per_node := getenv("MV2_COMM_WORLD_LOCAL_SIZE")):
            where = "MV2"

    elif (nodes := getenv("SLURM_JOB_NUM_NODES")):
        if (ranks := getenv("SLURM_NTASKS")):
            assert ranks % nodes == 0
            ranks_per_node = ranks // nodes
            where = "SLURM"

    else:
        nodes = defaults.LEGATE_NODES
        ranks_per_node = defaults.LEGATE_RANKS_PER_NODE

    nodes_kw["default"] = nodes
    ranks_per_node_kw["default"] = ranks_per_node

    if where:
        extra = f" [default auto-detected from {where}]"
        nodes_kw["help"] += extra
        ranks_per_node_kw["help"] += extra

    return nodes_kw, ranks_per_node_kw
```

then e.g. 
```
dev310 ❯ OMPI_COMM_WORLD_SIZE=4 OMPI_COMM_WORLD_LOCAL_SIZE=2 legate --help 
```
yields:
```
  --nodes NODES         Number of nodes to use [default auto-detected from OMPI] (default: 4)
  --ranks-per-node RANKS_PER_NODE
                        Number of ranks (processes running copies of the program) to launch per node. [default auto-detected from OMPI] (default: 2)


```

**Comment by manopapad** [comment]
Yes, let's just do that, no need to bend over backwards if we don't have the required information anyway.

> defaults replacement

That's nifty!
