### ISSUE TITLE
New warnings on non-editable build

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#862]
@bryevdv does anything look concerning?

```
  -- Installing: /home/mpapadakis/noneditable/legate.core/_skbuild/linux-x86_64-3.10/cmake-install/lib/liblegion_canonical_python.so
  '/home/mpapadakis/noneditable/env/bin/python3' '-m' 'pip' 'install' '--global-option=--cmake-build-dir' '--global-option=/home/mpapadakis/noneditable/legate.core/_skbuild/linux-x86_64-3.10/cmake-build/_deps/legion-build/runtime' '--global-option=--prefix' '--global-option=/home/mpapadakis/noneditable/legate.core/_skbuild/linux-x86_64-3.10/cmake-install' '--ignore-installed' '--root' '/' '--prefix' '/home/mpapadakis/noneditable/env' '.'
  DEPRECATION: --build-option and --global-option are deprecated. pip 24.0 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
  WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option.
```

```
  /home/mpapadakis/noneditable/env/lib/python3.10/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'legate.core._lib' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'legate.core._lib' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

          This leads to an ambiguous overall configuration. If you want to distribute this
          package, please make sure that 'legate.core._lib' is explicitly added
          to the `packages` configuration field.

          Alternatively, you can also rely on setuptools' discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

          If you don't want 'legate.core._lib' to be distributed and are
          already explicitly excluding 'legate.core._lib' via
          `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
          you can try to use `exclude_package_data`, or `include-package-data=False` in
          combination with a more fine grained `package-data` configuration.

          You can read more about "package data files" on setuptools documentation page:

          - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


          [^1]: For Python, any directory (with suitable naming) can be imported,
                even if it does not contain any `.py` files.
                On the other hand, currently there is no concept of package data
                directory, all directories are treated like packages.
          ********************************************************************************

  !!
```

```
WARNING: There was an error checking the latest version of pip.
See below for error
Traceback (most recent call last):
  File "/home/mpapadakis/noneditable/env/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 227, in pip_self_version_check
    upgrade_prompt = _self_version_check_logic(
  File "/home/mpapadakis/noneditable/env/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 188, in _self_version_check_logic
    remote_version_str = state.get(current_time)
  File "/home/mpapadakis/noneditable/env/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 76, in get
    last_check = datetime.datetime.fromisoformat(self._state["last_check"])
ValueError: Invalid isoformat string: '2023-08-30T23:44:26Z'
```

**Comment by manopapad** [comment]
Full build output: 
[temp3.txt](https://github.com/nv-legate/legate.core/files/12922450/temp3.txt)

**Comment by bryevdv** [comment]
Seems to be known upstream: https://github.com/pypa/pip/issues/12338

**Comment by manopapad** [comment]
What about the other two?

**Comment by bryevdv** [comment]
> DEPRECATION: --build-option and --global-option are deprecated

Based on some replies at https://github.com/pypa/pip/issues/11859 and https://github.com/pypa/setuptools/issues/3896 it seems like this might be a current workaround:
```
 --config-setting="--global-option=--verbose"  .
```
which seems pretty unpleasant but at a glance at least it doesn't look like there would be any delicate quoting issues. 

I guess a longer term solution would be to try to switch to use [`build`](https://pypi.org/project/build/`) instead, but I am not sure up front how involved that would be.

**Comment by bryevdv** [comment]
> Python recognizes 'legate.core._lib' as an importable package

This seem like maybe just a change to `find_packages` config, e.g. just add `legate.core._lib`. Right now there is a wildcard but maybe that does not (or recently does not) include "private" underscore dirs by default (speculation at this point)

**Comment by bryevdv** [comment]
@manopapad regarding the error from the datetime check in `pip`, [this comment](https://github.com/pypa/pip/issues/12357#issuecomment-1766680555) suggests setting `PIP_DISABLE_PIP_VERSION_CHECK=1` as an immediate workaround (and also maybe a good setting for CI environments in any case)

**Comment by bryevdv** [comment]
Regarding the `global-option` I don't see where we are setting that ourselves anywhere, and it looks like the immediate preceding command is 
```
  [220/221] cd /home/mpapadakis/noneditable/legate.core/_skbuild/linux-x86_64-3.10/cmake-build && /home/mpapadakis/noneditable/env/bin/cmake -P cmake_install.cmake
```
so I suspect this issue may actually originating in scikit-build

**Comment by manopapad** [comment]
> context.pyx  types.pyx
> Do any of those actually need to be distributed?

No, AFAIK these should all be used exclusively by cython. 

> Edit2: adding a bogus __init__.py gets rid of the warning

Do you mind making a PR with this, and asking @Jacobfaib to verify it's good?

> regarding the error from the datetime check in pip, https://github.com/pypa/pip/issues/12357#issuecomment-1766680555 suggests setting PIP_DISABLE_PIP_VERSION_CHECK=1 as an immediate workaround

Presumably the bug has been fixed https://github.com/pypa/pip/issues/12357#issuecomment-1766645762, so I'm inclined to just leave this alone.

**Comment by manopapad** [comment]
You're right, here it is https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/CMakeLists.txt?ref_type=heads#L75. 

If you know how to fix this, can you please submit a PR against Legion?

**Comment by bryevdv** [comment]
I've already been looking at a few different approached but unfortunately no success yet, the build dir is not getting communicated and results in a compilation error for a missing header

**Comment by bryevdv** [comment]
I have tried a bunch of various incantations with `--config-settings` but none have worked. AFAICT it comes down to this bit inside  `legion/bindings/python/setup.py`
```python
# Hack: I can't get initialize/finalize_option to work, so just parse
# the arguments here...
parser = argparse.ArgumentParser()
parser.add_argument('--cmake-build-dir', required=False)
parser.add_argument('--prefix', required=False)
args, unknown = parser.parse_known_args()
sys.argv[1:] = unknown
```
*What I think the case is*: to the extent that `--config-setting` can be used to tunnel `--global-setting` through to `setuptools`, that *won't happen via command line options* to an actually invoked-as-script `setup.py` (i.e. handling `sys.argv` here would no longer be effective). 

printing `sys.argv` in the the `setup.py` seems to confirm this:
```
 ['setup.py', 'bdist_wheel', '--dist-dir', '/tmp/pip-wheel-4nb3s7fa/.tmp-i2j3txai']
```

One way to work around this would be to rely on env vars instead of command line options. This is actually what the folks on DPO Packaging advised me on another project in the last year. But before embarking on that, I guess I'd like to know if there is any expected movement on larger efforts, i.e. IIRC there was some talk of switching legion to `scikit-build` or something.

**Comment by manopapad** [comment]
There is an ongoing discussion about transitioning Legion to a more standards-compliant build workflow https://github.com/StanfordLegion/legion/issues/1317, so let's hold off on doing drastic changes.

In that case, I think all the warnings have been sufficiently addressed (or punted), so I'll close this.
