### ISSUE TITLE
Python tasks support Optional arguments

### ISSUE THREAD

**Issue by syamajala** [nv-legate/legate.core#955]
It would be really nice if Python tasks could support taking Optional type arguments and if they could return futures for scalars instead of just None.

**Comment by manopapad** [comment]
> if they could return futures for scalars instead of just None

We're gonna be pushing support for "reduction" stores. If the top-level store has volume=1, then it will be backed by a Future, and the "contributions" of the different tasks will be accumulated automatically with a FutureMap reduction. Would this cover you?

**Comment by Jacobfaib** [comment]
@syamajala could you elaborate on what syntax you would like to be allowed?

**Comment by syamajala** [comment]
For Python tasks something like this:
```
@task(
    variants=("cpu", "gpu")
)
def fit_wrapper(data: InputStore,
                weights: Union[InputStore, None],
                model_id: int,
                initial_parameters: InputStore, _: OutputStore,
                tolerance: Optional[float] = None,
                max_number_iterations: Optional[int] = None,
                parameters_to_fit: Optional[InputStore] = None,
                estimator_id: Optional[int] = None,
                user_info: Optional[InputStore] = None) -> None:
```

I guess Union is also needed if the argument does not have a default value.  

The reduction store for scalars should be enough for now. It will be nice to eventually be able to do more complicated stuff too though.

**Comment by manopapad** [comment]
I think for our sanity, we want to restrict the ask to supporting `Optional[*Store]` / `Union[*Store, None]`. It is unclear what the semantics of more general `Union`s even would be. And from a private discussion with @Jacobfaib, it seems we also want to restrict the possibly default values to `None`.

**Comment by Jacobfaib** [comment]
The upcoming release (24.09) will now support optional (i.e. `= None`) arguments for stores. As an added bonus, it will also support arbitrary default values for scalar values. So you will now be able to write
```python
from legate.task import task, InputStore

@task
def foo(x: InputStore | None = None, y: dict[str, int] = {"foo": 1, "bar": 600}) -> None:
    assert x is None
	assert y == {"foo": 1, "bar": 600}

foo()
```
